### ISSUE TITLE
Substrate failed to build with latest wasmi 0.4.5

### ISSUE THREAD

**Issue by xlc** [paritytech/wasmi#178]
0.4.3 works

```
*** Building wasm binaries in runtime/wasm
   Compiling proc-macro2 v0.4.28
   Compiling wasmi-validation v0.1.0
error[E0432]: unresolved import `hashbrown`
  --> /Users/bryanchen/.cargo/registry/src/github.com-1ecc6299db9ec823/wasmi-validation-0.1.0/src/lib.rs:31:5
   |
31 | use hashbrown::HashSet;
   |     ^^^^^^^^^ use of undeclared type or module `hashbrown`

warning: ignoring -C extra-filename flag due to -o flag

error: aborting due to previous error

For more information about this error, try `rustc --explain E0432`.
error: Could not compile `wasmi-validation`.
warning: build failed, waiting for other jobs to finish...
error: build failed
```

`hashbrown` is used in no_std build
https://github.com/paritytech/wasmi/blob/a3aad8a549392ab70748b52e52f4f96ed80e2b3c/validation/src/lib.rs#L31

I think https://github.com/paritytech/wasmi/blob/master/validation/Cargo.toml needs updating?

**Comment by xlc** [comment]
My bad not including core feature.

**Comment by drewstone** [comment]
@xlc How did you solve this issue?

**Comment by xlc** [comment]
Add contract/core feature and enable it by default

https://github.com/cennznet/cennznet/blob/a4163c2be3b6ab07e35b6977c2b74af5b5ea2e24/runtime/Cargo.toml#L51
https://github.com/cennznet/cennznet/blob/a4163c2be3b6ab07e35b6977c2b74af5b5ea2e24/runtime/wasm/Cargo.toml#L17
https://github.com/cennznet/cennznet/blob/a4163c2be3b6ab07e35b6977c2b74af5b5ea2e24/runtime/wasm/Cargo.toml#L15
